In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('beijing_dataset.csv')

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df.head()

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

In [9]:
df.drop(columns='No')

       year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd     Iws  Is  Ir
0      2010      1    1     0    NaN   -21 -11.0  1021.0   NW    1.79   0   0
1      2010      1    1     1    NaN   -21 -12.0  1020.0   NW    4.92   0   0
2      2010      1    1     2    NaN   -21 -11.0  1019.0   NW    6.71   0   0
3      2010      1    1     3    NaN   -21 -14.0  1019.0   NW    9.84   0   0
4      2010      1    1     4    NaN   -20 -12.0  1018.0   NW   12.97   0   0
...     ...    ...  ...   ...    ...   ...   ...     ...  ...     ...  ..  ..
43819  2014     12   31    19    8.0   -23  -2.0  1034.0   NW  231.97   0   0
43820  2014     12   31    20   10.0   -22  -3.0  1034.0   NW  237.78   0   0
43821  2014     12   31    21   10.0   -22  -3.0  1034.0   NW  242.70   0   0
43822  2014     12   31    22    8.0   -22  -4.0  1034.0   NW  246.72   0   0
43823  2014     12   31    23   12.0   -21  -3.0  1034.0   NW  249.85   0   0

[43824 rows x 12 columns]

In [10]:
df.isnull().sum()

No          0
year        0
month       0
day         0
hour        0
pm2.5    2067
DEWP        0
TEMP        0
PRES        0
cbwd        0
Iws         0
Is          0
Ir          0
dtype: int64

In [11]:
df.describe()

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,Iws,Is,Ir
count,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,41757.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000
mean,21912.500000,2012.000000,6.523549,15.727820,11.500000,98.613215,1.817246,12.448521,1016.447654,23.889140,0.052734,0.194916
std,12651.043435,1.413842,3.448572,8.799425,6.922266,92.050387,14.433440,12.198613,10.268698,50.010635,0.760375,1.415867
min,1.000000,2010.000000,1.000000,1.000000,0.000000,0.000000,-40.000000,-19.000000,991.000000,0.450000,0.000000,0.000000
25%,10956.750000,2011.000000,4.000000,8.000000,5.750000,29.000000,-10.000000,2.000000,1008.000000,1.790000,0.000000,0.000000
50%,21912.500000,2012.000000,7.000000,16.000000,11.500000,72.000000,2.000000,14.000000,1016.000000,5.370000,0.000000,0.000000
75%,32868.250000,2013.000000,10.000000,23.000000,17.250000,137.000000,15.000000,23.000000,1025.000000,21.910000,0.000000,0.000000
max,43824.000000,2014.000000,12.000000,31.000000,23.000000,994.000000,28.000000,42.000000,1046.000000,585.600000,27.000000,36.000000

In [12]:
df.dropna(subset=['pm2.5'])

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,cbwd,Iws,Is,Ir
24,25,2010,1,2,0,129.0,-16,-4.0,1020.0,SE,1.79,0,0
25,26,2010,1,2,1,148.0,-15,-4.0,1020.0,SE,2.68,0,0
26,27,2010,1,2,2,159.0,-11,-5.0,1021.0,SE,3.57,0,0
27,28,2010,1,2,3,181.0,-7,-5.0,1022.0,SE,5.36,1,0
28,29,2010,1,2,4,138.0,-7,-5.0,1022.0,SE,6.25,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43819,43820,2014,12,31,19,8.0,-23,-2.0,1034.0,NW,231.97,0,0
43820,43821,2014,12,31,20,10.0,-22,-3.0,1034.0,NW,237.78,0,0
43821,43822,2014,12,31,21,10.0,-22,-3.0,1034.0,NW,242.70,0,0
43822,43823,2014,12,31,22,8.0,-22,-4.0,1034.0,NW,246.72,0,0
43823,43824,2014,12,31,23,12.0,-21,-3.0,1034.0,NW,249.85,0,0

In [16]:
df['cbwd'].value_counts()

cbwd
SE    15290
NW    14150
cv     9387
NE     4997
Name: count, dtype: int64

In [ ]:
df

AttributeError: 'list' object has no attribute 'value_counts'